### ISSUE TITLE
THUMOS14 testing error

### ISSUE THREAD

**Issue by borijang** [boheumd/ASM-Loc#1]
Hi, thanks for your work! I tried testing your model on THUMOS14, downloaded all the files, but I am getting an error. I am on macOS 12.4, python 3.8, with installed requirements.

This is the output for the command `python main_THUMOS.py --batch_size 1 --test --checkpoint saved_model/THUMOS`:

load checkpoint from saved_model/THUMOS/model_step0_last_epoch.pth
  0%|          | 0/210 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/Users/borijang/Projects/ASM-Loc/main_THUMOS.py", line 620, in <module>
    main(args)
  File "/Users/borijang/Projects/ASM-Loc/main_THUMOS.py", line 594, in main
    test_log_dict = test(args, model, test_dataloader, criterion, logger=logger)
  File "/Users/borijang/Projects/ASM-Loc/main_THUMOS.py", line 113, in test
    for vid_name, input_feature, vid_label, vid_len, proposal_bbox, proposal_count_by_video, pseudo_instance_label, dynamic_segment_weights_cumsum in tqdm(dataloader):
  File "/opt/miniconda3/envs/asmloc/lib/python3.8/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/opt/miniconda3/envs/asmloc/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 438, in __iter__
    return self._get_iterator()
  File "/opt/miniconda3/envs/asmloc/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 384, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/opt/miniconda3/envs/asmloc/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1048, in __init__
    w.start()
  File "/opt/miniconda3/envs/asmloc/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/opt/miniconda3/envs/asmloc/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/opt/miniconda3/envs/asmloc/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/opt/miniconda3/envs/asmloc/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/opt/miniconda3/envs/asmloc/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/opt/miniconda3/envs/asmloc/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/opt/miniconda3/envs/asmloc/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle '_io.TextIOWrapper' object

**Comment by borijang** [comment]
Okay so looks like this error comes from a change in the [multiprocessing library](https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods):

> Changed in version 3.8: On macOS, the spawn start method is now the default.

This is also a relevant pytorch issue: https://github.com/pytorch/pytorch/issues/70344. Setting num_workers to 0 "fixes" this issue.
