### ISSUE TITLE
error training what can be problem 

### ISSUE THREAD

**Issue by asifraza151** [boheumd/ASM-Loc#8]
F:\ProgramData\Anaconda3\envs\alm\python.exe D:/raza/ASM-Loc-main/main_THUMOS.py --batch_size 16
Traceback (most recent call last):
  File "D:/raza/ASM-Loc-main/main_THUMOS.py", line 655, in <module>
    main(args)
  File "D:/raza/ASM-Loc-main/main_THUMOS.py", line 573, in main
    train(args, model, train_dataloader, criterion, optimizer, epoch_idx, logger=logger, step=step,
  File "D:/raza/ASM-Loc-main/main_THUMOS.py", line 41, in train
    dynamic_segment_weights_cumsum] in enumerate(dataloader):
  File "F:\ProgramData\Anaconda3\envs\alm\lib\site-packages\torch\utils\data\dataloader.py", line 355, in __iter__
    return self._get_iterator()
  File "F:\ProgramData\Anaconda3\envs\alm\lib\site-packages\torch\utils\data\dataloader.py", line 301, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "F:\ProgramData\Anaconda3\envs\alm\lib\site-packages\torch\utils\data\dataloader.py", line 914, in __init__
    w.start()
  File "F:\ProgramData\Anaconda3\envs\alm\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "F:\ProgramData\Anaconda3\envs\alm\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "F:\ProgramData\Anaconda3\envs\alm\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "F:\ProgramData\Anaconda3\envs\alm\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "F:\ProgramData\Anaconda3\envs\alm\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle '_io.TextIOWrapper' object

**Comment by asifraza151** [comment]
Hi Sir, thanks for your work! I tried to train/test your model on THUMOS14, and downloaded all the files as per your instruction but having an error. Kindly guide me if you know the solution for the above error.

**Comment by asifraza151** [comment]
TypeError: cannot pickle '_io.TextIOWrapper' object

**Comment by boheumd** [comment]
Hi, thank you for your interest in our work. I saw you are running the code on a Windows machine. Could you please try it on a Linux environment? It is weird because I never saw this error before, so changing to Linux might help solve this.

**Comment by CL2LC** [comment]
Do not use logger may help. I closed it by 'logger = None' order and it worked.

**Comment by asifraza151** [comment]
yes, i tried both solutions but logger is some thing good. so I moved to ubuntu. problem solved thanks guys
